databases:
  - name: ecommerce_production
    databaseName: ecommerce_production
    user: ecommerce_production
    plan: free

services:
  - type: web
    name: ecommerce
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/rails db:create && ./bin/rails db:migrate && ./bin/rails server && bin/rails tailwindcss:watch"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
